// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Add from '../src/commands/add.js'
import Board from '../src/commands/board.js'
import Boards from '../src/commands/boards.js'
import Check from '../src/commands/check.js'
import Clear from '../src/commands/clear.js'
import Config from '../src/commands/config.js'
import Delete from '../src/commands/delete.js'
import Entity from '../src/commands/entity.js'
import Install from '../src/commands/install.js'
import List from '../src/commands/list.js'
import Migrations from '../src/commands/migrations.js'
import Pull from '../src/commands/pull.js'
import Rebuild from '../src/commands/rebuild.js'
import Recover from '../src/commands/recover.js'
import Set from '../src/commands/set.js'
import Star from '../src/commands/star.js'
import Sync from '../src/commands/sync.js'
import Theme from '../src/commands/theme.js'
import Truncate from '../src/commands/truncate.js'
import Uncheck from '../src/commands/uncheck.js'
import Unstar from '../src/commands/unstar.js'
import Update from '../src/commands/update.js'
import Use from '../src/commands/use.js'
import Workspace from '../src/commands/workspace.js'
import Workspaces from '../src/commands/workspaces.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['add', 'board', 'boards', 'check', 'clear', 'config', 'delete', 'entity', 'install', 'list', 'migrations', 'pull', 'rebuild', 'recover', 'set', 'star', 'sync', 'theme', 'truncate', 'uncheck', 'unstar', 'update', 'use', 'workspace', 'workspaces'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'add': Add,
  'board': Board,
  'boards': Boards,
  'check': Check,
  'clear': Clear,
  'config': Config,
  'delete': Delete,
  'entity': Entity,
  'install': Install,
  'list': List,
  'migrations': Migrations,
  'pull': Pull,
  'rebuild': Rebuild,
  'recover': Recover,
  'set': Set,
  'star': Star,
  'sync': Sync,
  'theme': Theme,
  'truncate': Truncate,
  'uncheck': Uncheck,
  'unstar': Unstar,
  'update': Update,
  'use': Use,
  'workspace': Workspace,
  'workspaces': Workspaces
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'add': {
      name: 'add',
      description: 'add a task (d:[…] date, r:[…] recurrence, b:[…] board)',
      path: './src/commands/add'
    },
  'board': {
      name: 'board',
      description: 'create, list and edit boards',
      path: './src/commands/board'
    },
  'boards': {
      name: 'boards',
      description: 'list boards (shortcut for `board list`)',
      path: './src/commands/boards'
    },
  'check': {
      name: 'check',
      description: 'complete a task',
      path: './src/commands/check'
    },
  'clear': {
      name: 'clear',
      description: 'remove an already-deleted task from this machine',
      path: './src/commands/clear'
    },
  'config': {
      name: 'config',
      description: 'open settings (piped: print them)',
      path: './src/commands/config'
    },
  'delete': {
      name: 'delete',
      description: 'soft-delete a task',
      path: './src/commands/delete'
    },
  'entity': {
      name: 'entity',
      description: 'author a structural migration for an entity folder (plumber)',
      path: './src/commands/entity'
    },
  'install': {
      name: 'install',
      description: 'first-run scaffold and setup',
      options: {
        'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'reinstall over an existing install', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":830,"end":835,"loc":{"start":{"line":21,"column":45,"index":830},"end":{"line":21,"column":50,"index":835}},"value":false}}]}, validator: '(val) => true' },
        'date-format': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'date order to use when piped', enumValues: ["america","europe"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'nerdfont': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'use nerdfont glyphs when piped', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1110,"end":1115,"loc":{"start":{"line":28,"column":48,"index":1110},"end":{"line":28,"column":53,"index":1115}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/install'
    },
  'list': {
      name: 'list',
      description: 'list tasks',
      options: {
        'global': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'list across every workspace', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1367,"end":1372,"loc":{"start":{"line":48,"column":46,"index":1367},"end":{"line":48,"column":51,"index":1372}},"value":false}}]}, validator: '(val) => true' },
        'checked': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'include completed tasks', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1510,"end":1515,"loc":{"start":{"line":52,"column":47,"index":1510},"end":{"line":52,"column":52,"index":1515}},"value":false}}]}, validator: '(val) => true' },
        'deleted': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'show the bin instead of the live tasks', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1649,"end":1654,"loc":{"start":{"line":56,"column":47,"index":1649},"end":{"line":56,"column":52,"index":1654}},"value":false}}]}, validator: '(val) => true' },
        'starred': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'only starred tasks', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1803,"end":1808,"loc":{"start":{"line":60,"column":47,"index":1803},"end":{"line":60,"column":52,"index":1808}},"value":false}}]}, validator: '(val) => true' },
        'hasDescription': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'only tasks that carry a description', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1944,"end":1949,"loc":{"start":{"line":64,"column":54,"index":1944},"end":{"line":64,"column":59,"index":1949}},"value":false}}]}, validator: '(val) => true' },
        'period': { type: 'z.string.optional', required: false, hasDefault: false, description: 'only tasks due within a window, e.g. 2d, 3m, 1y', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'in-board': { type: 'z.string.optional', required: false, hasDefault: false, description: 'only tasks on a board (name, number or inbox)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/list'
    },
  'migrations': {
      name: 'migrations',
      description: 'report applied and pending migrations',
      path: './src/commands/migrations'
    },
  'pull': {
      name: 'pull',
      description: 'replay peers\' events into this workspace',
      path: './src/commands/pull'
    },
  'rebuild': {
      name: 'rebuild',
      description: 're-derive this workspace from the consolidated snapshot',
      path: './src/commands/rebuild'
    },
  'recover': {
      name: 'recover',
      description: 'restore a deleted task',
      path: './src/commands/recover'
    },
  'set': {
      name: 'set',
      description: 'edit a task field',
      path: './src/commands/set'
    },
  'star': {
      name: 'star',
      description: 'star a task',
      path: './src/commands/star'
    },
  'sync': {
      name: 'sync',
      description: 'publish this peer\'s events to the remote',
      path: './src/commands/sync'
    },
  'theme': {
      name: 'theme',
      description: 'open the theme editor',
      path: './src/commands/theme'
    },
  'truncate': {
      name: 'truncate',
      description: 'bound a branch\'s history to its most recent commits',
      options: {
        'keep': { type: 'z.coerce.number.int.min', required: true, hasDefault: false, description: 'the number of commits to keep', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":421,"end":422,"loc":{"start":{"line":12,"column":45,"index":421},"end":{"line":12,"column":46,"index":422}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'branch': { type: 'z.string.optional', required: false, hasDefault: false, description: 'the branch to truncate (default: this peer\'s own)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/truncate'
    },
  'uncheck': {
      name: 'uncheck',
      description: 'reopen a task',
      path: './src/commands/uncheck'
    },
  'unstar': {
      name: 'unstar',
      description: 'remove a task\'s star',
      path: './src/commands/unstar'
    },
  'update': {
      name: 'update',
      description: 'self-update from GitHub',
      options: {
        'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'check even if the cached answer is still fresh', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":951,"end":956,"loc":{"start":{"line":31,"column":54,"index":951},"end":{"line":31,"column":59,"index":956}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/update'
    },
  'use': {
      name: 'use',
      description: 'switch the current workspace (shortcut for `workspace use`)',
      path: './src/commands/use'
    },
  'workspace': {
      name: 'workspace',
      description: 'create, switch and remove workspaces',
      path: './src/commands/workspace'
    },
  'workspaces': {
      name: 'workspaces',
      description: 'list workspaces (shortcut for `workspace list`)',
      path: './src/commands/workspaces'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
